{ pkgs ? import <nixpkgs> { } }:

pkgs.mkShell {
  buildInputs = [
    pkgs.nodejs
    pkgs.python3
  ];

  shellHook = ''
    # Install dependencies
    npm install
  '';

  phases = [ "installPhase" "buildPhase" "startPhase" ];

  installPhase = ''
    # Install dependencies
    npm install
  '';

  buildPhase = ''
    # Build the project
    npm run build
  '';

  startPhase = ''
    # Start the project
    npm run start
  '';
}