
providers = ["...", "python"]

[phases.setup]
aptPkgs = [
    '...',
    "build-essential",
    "libx11-dev",
    "libxi-dev",
    "libxext-dev",
    'libpixman-1-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    "libglu1-mesa-dev",
    "libgl1-mesa-dev",
    "libgstreamer1.0-dev",
    "pkg-config",
]
commands = [
    '...',
    "sed -i '21i#include <cstdint>' node_modules/gl/angle/src/common/angleutils.h"
]